### ISSUE TITLE
ERR_WORKER_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by cmunyoz** [soltecsis/fwcloud-api#569]
```shell
Apr 13 10:25:42 fwcloud-01 fwcloud-api[1505]: events.js:291
Apr 13 10:25:42 fwcloud-01 fwcloud-api[1505]:       throw er; // Unhandled 'error' event
Apr 13 10:25:42 fwcloud-01 fwcloud-api[1505]:       ^
Apr 13 10:25:42 fwcloud-01 fwcloud-api[1505]: Error [ERR_WORKER_OUT_OF_MEMORY]: Worker terminated due to reaching memory limit: JS heap out of memory
Apr 13 10:25:42 fwcloud-01 fwcloud-api[1505]:     at Worker.[kOnExit] (internal/worker.js:229:26)
Apr 13 10:25:42 fwcloud-01 fwcloud-api[1505]:     at Worker.<computed>.onexit (internal/worker.js:165:20)
Apr 13 10:25:42 fwcloud-01 fwcloud-api[1505]: Emitted 'error' event on Worker instance at:
Apr 13 10:25:42 fwcloud-01 fwcloud-api[1505]:     at Worker.[kOnExit] (internal/worker.js:229:12)
Apr 13 10:25:42 fwcloud-01 fwcloud-api[1505]:     at Worker.<computed>.onexit (internal/worker.js:165:20) {
Apr 13 10:25:42 fwcloud-01 fwcloud-api[1505]:   code: 'ERR_WORKER_OUT_OF_MEMORY'
Apr 13 10:25:42 fwcloud-01 fwcloud-api[1505]: }
Apr 13 10:25:42 fwcloud-01 fwcloud-api[1505]: npm ERR! code ELIFECYCLE
Apr 13 10:25:42 fwcloud-01 fwcloud-api[1505]: npm ERR! errno 1
Apr 13 10:25:42 fwcloud-01 fwcloud-api[1505]: npm ERR! FWCloud-API@1.4.3 start: `node dist/src/bin/fwcloud`
Apr 13 10:25:42 fwcloud-01 fwcloud-api[1505]: npm ERR! Exit status 1
Apr 13 10:25:42 fwcloud-01 fwcloud-api[1505]: npm ERR!
Apr 13 10:25:42 fwcloud-01 fwcloud-api[1505]: npm ERR! Failed at the FWCloud-API@1.4.3 start script.
Apr 13 10:25:42 fwcloud-01 fwcloud-api[1505]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Apr 13 10:25:42 fwcloud-01 fwcloud-api[1505]: npm ERR! A complete log of this run can be found in:
Apr 13 10:25:42 fwcloud-01 fwcloud-api[1505]: npm ERR!     /home/fwcloud/.npm/_logs/2022-04-13T08_25_42_885Z-debug.log
Apr 13 10:25:42 fwcloud-01 systemd[1]: fwcloud-api.service: Main process exited, code=exited, status=1/FAILURE
Apr 13 10:25:42 fwcloud-01 systemd[1]: fwcloud-api.service: Failed with result 'exit-code'.
```

**Comment by cmunyoz** [comment]
The problem is not solved yet.
<img width="1432" alt="Captura de pantalla 2022-10-06 a las 11 39 06" src="https://user-images.githubusercontent.com/28894874/194923893-ec147e65-307f-4f81-81b6-b9c64ab7b082.png">

**Comment by cmunyoz** [comment]
It has happen in on installation today at: 17 nov 2022 13:23:37 UTC

Deleting some records the problem has been temporary solved:
delete from openvpn_status_history where timestamp <= UNIX_TIMESTAMP(STR_TO_DATE('2022-10-15', '%Y-%m-%d'));

**Comment by cmunyoz** [comment]
The worker generates a query like this:
```sql
SELECT `history`.`id` AS `history_id`, `history`.`name` AS `history_name`, `history`.`address` AS `history_address`, `history`.`bytes_received` AS `history_bytes_received`, `history`.`bytes_sent` AS `history_bytes_sent`, `history`.`connected_at_timestamp` AS `history_connected_at_timestamp`, `history`.`disconnected_at_timestamp` AS `history_disconnected_at_timestamp`, `history`.`timestamp` AS `history_timestamp`, `history`.`openvpn_server_id` AS `history_openvpn_server_id` FROM `openvpn_status_history` `history` WHERE `history`.`openvpn_server_id` = 68 ORDER BY `history`.`timestamp` DESC
```

This a slow query because there is no index for the fields `openvpn_server_id`and `timestamp`. 
- [ ] It is necessary to create a database migration that creates such index.

This query returns more than 4 millions of records that must be processed by the worker. And increases as more records are added to the database. 
- [ ] We must limit the amount of information returned because the worker doesn't needs all these information.

**Comment by cmunyoz** [comment]
The problem is that the `getOne()` method of TypeORM returns only one object but gets all rows from the data base engine!

In the `src/models/vpn/openvpn/status/openvpn-status-history.service.ts` file we have this code that uses such `getOne()` method:
```ts
        // Get the last entry already persisted from the openvpn server. This entry is used to get  its timestamp as it will be used to
        // retrieve the last batch. If there is not lastEntry means there is not lastBatch thus all disconnect detection logic
        // won't be applied.
        const lastEntry: OpenVPNStatusHistory | undefined = await getRepository(OpenVPNStatusHistory).createQueryBuilder('history')
            .where('history.openVPNServerId = :openvpn', {openvpn: serverOpenVPN.id})
            .orderBy('history.timestampInSeconds', 'DESC')
            .getOne()
```

If we change it to this one and with the addition of the required indexes to the database, the problem is solved:
```ts
        // Get the last entry already persisted from the openvpn server. This entry is used to get  its timestamp as it will be used to
        // retrieve the last batch. If there is not lastEntry means there is not lastBatch thus all disconnect detection logic
        // won't be applied.
        const lastEntry: OpenVPNStatusHistory | undefined = await getRepository(OpenVPNStatusHistory).createQueryBuilder('history')
            .where('history.openVPNServerId = :openvpn', {openvpn: serverOpenVPN.id})
            .orderBy('history.timestampInSeconds', 'DESC')
            .limit(1)
            .getOne()
```
